/**
 * 서울 이벤트 데이터
 * category: 'festival' | 'popup' | 'concert' | 'exhibition' | 'market' | 'party'
 */
const CITY_EVENTS = [
  // ─── 축제 ────────────────────────────────────────────────────────────────
  {
    id: "f1",
    title: "여의도 봄꽃 축제",
    category: "festival",
    startDate: "2026-04-01",
    endDate: "2026-04-20",
    venueName: "한강공원 여의도지구",
    address: "서울 영등포구 여의동로 330",
    lat: 37.5285,
    lng: 126.9326,
    description:
      "여의도 한강공원에서 펼쳐지는 봄꽃 축제. 벚꽃, 개나리, 유채꽃이 한자리에.",
    price: "무료",
    tags: ["벚꽃", "봄", "한강", "가족", "데이트"],
  },
  {
    id: "f2",
    title: "서울 봄 어웨이크닝 페스티벌",
    category: "festival",
    startDate: "2026-04-19",
    endDate: "2026-04-20",
    venueName: "올림픽공원 88잔디마당",
    address: "서울 송파구 올림픽로 424",
    lat: 37.522,
    lng: 127.1175,
    description:
      "봄 햇살 아래 야외 음악 페스티벌. 인디, 팝, 일렉트로닉 장르 아티스트 총출동.",
    price: "55,000원~",
    tags: ["음악", "야외", "페스티벌", "인디"],
  },
  {
    id: "f3",
    title: "망원 봄 나들이 축제",
    category: "festival",
    startDate: "2026-04-12",
    endDate: "2026-04-13",
    venueName: "망원 한강공원",
    address: "서울 마포구 망원동 402",
    lat: 37.5523,
    lng: 126.8986,
    description:
      "망원 한강공원에서 열리는 봄 나들이 축제. 푸드트럭, 버스킹, 플리마켓.",
    price: "무료",
    tags: ["한강", "봄", "버스킹", "푸드트럭"],
  },
  {
    id: "f4",
    title: "건대 봄 크래프트 맥주 축제",
    category: "festival",
    startDate: "2026-04-11",
    endDate: "2026-04-13",
    venueName: "어린이대공원 앞 광장",
    address: "서울 광진구 능동로 120",
    lat: 37.5472,
    lng: 127.0826,
    description:
      "봄을 맞이하는 크래프트 맥주 & 푸드 페스티벌. 50여 개 브루어리 참가.",
    price: "입장 무료",
    tags: ["맥주", "푸드", "봄", "크래프트"],
  },

  // ─── 팝업 ────────────────────────────────────────────────────────────────
  {
    id: "p1",
    title: "New Balance 성수 팝업",
    category: "popup",
    startDate: "2026-04-05",
    endDate: "2026-04-30",
    venueName: "성수동 연무장길",
    address: "서울 성동구 연무장15길 11",
    lat: 37.5447,
    lng: 127.0558,
    description:
      "뉴발란스 2026 S/S 컬렉션 팝업. 한정판 스니커즈 & 커스텀 서비스 운영.",
    price: "무료 입장",
    tags: ["스니커즈", "패션", "성수", "한정판"],
  },
  {
    id: "p2",
    title: "무신사 스탠다드 팝업",
    category: "popup",
    startDate: "2026-04-10",
    endDate: "2026-04-20",
    venueName: "성수 무신사 팝업존",
    address: "서울 성동구 아차산로17나길 49",
    lat: 37.5461,
    lng: 127.0572,
    description:
      "무신사 스탠다드 봄 신상품 팝업. 특별 할인 및 한정 굿즈 증정 이벤트.",
    price: "무료 입장",
    tags: ["패션", "성수", "굿즈", "할인"],
  },
  {
    id: "p3",
    title: "스타벅스 리저브 팝업",
    category: "popup",
    startDate: "2026-04-15",
    endDate: "2026-04-25",
    venueName: "코엑스 아티움",
    address: "서울 강남구 영동대로 513",
    lat: 37.5115,
    lng: 127.0582,
    description: "스타벅스 리저브 한정 굿즈 팝업. 봄 시즌 텀블러·컵 한정 발매.",
    price: "무료 입장",
    tags: ["스타벅스", "굿즈", "코엑스", "강남"],
  },
  {
    id: "p4",
    title: "아디다스 삼바 팝업",
    category: "popup",
    startDate: "2026-04-08",
    endDate: "2026-04-21",
    venueName: "홍대 플래그십",
    address: "서울 마포구 어울마당로 35",
    lat: 37.5568,
    lng: 126.9232,
    description:
      "아디다스 삼바 스페셜 에디션 팝업. 포토부스 & 커스터마이징 존 운영.",
    price: "무료 입장",
    tags: ["아디다스", "홍대", "스니커즈", "한정"],
  },
  {
    id: "p5",
    title: "라인프렌즈 × 아티스트 팝업",
    category: "popup",
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    venueName: "DDP 살림터",
    address: "서울 중구 을지로 281",
    lat: 37.5669,
    lng: 127.009,
    description:
      "라인프렌즈 × 신진 아티스트 콜라보 팝업. 한정 굿즈 & 포토 스팟.",
    price: "무료 입장",
    tags: ["캐릭터", "DDP", "굿즈", "아트"],
  },
  {
    id: "p6",
    title: "ADER error 이태원 팝업",
    category: "popup",
    startDate: "2026-04-13",
    endDate: "2026-04-26",
    venueName: "이태원 플래그십",
    address: "서울 용산구 이태원로 196",
    lat: 37.5349,
    lng: 126.9927,
    description:
      "아더에러 2026 봄 컬렉션 팝업. 한정 컬러웨이 및 아카이브 전시.",
    price: "무료 입장",
    tags: ["아더에러", "패션", "이태원", "디자인"],
  },

  // ─── 콘서트 ──────────────────────────────────────────────────────────────
  {
    id: "c1",
    title: "아이유 서울 콘서트",
    category: "concert",
    startDate: "2026-04-18",
    endDate: "2026-04-19",
    venueName: "KSPO 돔",
    address: "서울 송파구 올림픽로 424",
    lat: 37.5186,
    lng: 127.1202,
    description: "아이유 HEREH WORLD TOUR 서울 공연. 1만 5천 석 단독 콘서트.",
    price: "110,000원~165,000원",
    tags: ["아이유", "K-POP", "콘서트", "단독"],
  },
  {
    id: "c2",
    title: "혁오 20주년 콘서트",
    category: "concert",
    startDate: "2026-04-12",
    endDate: "2026-04-12",
    venueName: "올림픽홀",
    address: "서울 송파구 올림픽로 424",
    lat: 37.52,
    lng: 127.1215,
    description:
      "혁오 데뷔 20주년 기념 단독 콘서트. 모든 세대를 위한 감동의 무대.",
    price: "99,000원",
    tags: ["혁오", "인디", "밴드", "20주년"],
  },
  {
    id: "c3",
    title: "이태원 재즈 클럽 나이트",
    category: "concert",
    startDate: "2026-04-05",
    endDate: "2026-04-30",
    venueName: "Once In A Blue Moon",
    address: "서울 용산구 이태원로29길 9",
    lat: 37.5352,
    lng: 126.9948,
    description:
      "매주 금·토 이태원 재즈 바 공연. 국내외 재즈 뮤지션들의 라이브.",
    price: "20,000원~",
    tags: ["재즈", "이태원", "라이브", "주말"],
  },
  {
    id: "c4",
    title: "홍대 인디씬 라이브 쇼케이스",
    category: "concert",
    startDate: "2026-04-05",
    endDate: "2026-04-30",
    venueName: "Club FF",
    address: "서울 마포구 어울마당로 35-1",
    lat: 37.554,
    lng: 126.9244,
    description: "매주 토요일 홍대 Club FF 인디 밴드 라이브 쇼케이스.",
    price: "10,000원~",
    tags: ["인디", "홍대", "밴드", "토요일"],
  },
  {
    id: "c5",
    title: "세종문화회관 봄 클래식 갈라",
    category: "concert",
    startDate: "2026-04-17",
    endDate: "2026-04-17",
    venueName: "세종문화회관 대극장",
    address: "서울 종로구 세종대로 175",
    lat: 37.5724,
    lng: 126.9764,
    description: "서울시립교향악단과 함께하는 봄 클래식 갈라 콘서트.",
    price: "30,000원~90,000원",
    tags: ["클래식", "오케스트라", "세종문화회관", "봄"],
  },

  // ─── 전시 ────────────────────────────────────────────────────────────────
  {
    id: "e1",
    title: "서울라이트 DDP 2026",
    category: "exhibition",
    startDate: "2026-03-20",
    endDate: "2026-05-31",
    venueName: "DDP 동대문디자인플라자",
    address: "서울 중구 을지로 281",
    lat: 37.5667,
    lng: 127.0094,
    description:
      "DDP 외벽 미디어파사드 전시. 봄 시즌 테마로 매일 밤 펼쳐지는 빛의 향연.",
    price: "무료",
    tags: ["미디어아트", "DDP", "야경", "무료"],
  },
  {
    id: "e2",
    title: "국립현대미술관 봄 기획전",
    category: "exhibition",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    venueName: "국립현대미술관 서울",
    address: "서울 종로구 삼청로 30",
    lat: 37.5796,
    lng: 126.977,
    description:
      "현대 한국 작가들의 봄 기획전시. 회화, 조각, 미디어 아트 200여 점.",
    price: "4,000원",
    tags: ["미술", "종로", "현대미술", "기획전"],
  },
  {
    id: "e3",
    title: "예술의전당 봄 사진전",
    category: "exhibition",
    startDate: "2026-04-05",
    endDate: "2026-05-10",
    venueName: "예술의전당 한가람미술관",
    address: "서울 서초구 남부순환로 2406",
    lat: 37.4779,
    lng: 127.0163,
    description:
      "세계 사진작가 50명의 한국 봄 풍경 사진전. 300여 점 작품 감상.",
    price: "12,000원",
    tags: ["사진", "예술의전당", "전시", "작가"],
  },
  {
    id: "e4",
    title: "아모레퍼시픽 뷰티 아트전",
    category: "exhibition",
    startDate: "2026-04-10",
    endDate: "2026-04-26",
    venueName: "아모레퍼시픽 미술관",
    address: "서울 용산구 한강대로 100",
    lat: 37.525,
    lng: 126.9813,
    description:
      "뷰티와 예술의 경계를 탐구하는 인터랙티브 전시. 디지털 아트와 뷰티의 융합.",
    price: "10,000원",
    tags: ["인터랙티브", "뷰티", "용산", "아트"],
  },
  {
    id: "e5",
    title: "성수 사진관 그룹전",
    category: "exhibition",
    startDate: "2026-04-13",
    endDate: "2026-04-27",
    venueName: "성수 아트 팩토리",
    address: "서울 성동구 성수이로 77",
    lat: 37.5464,
    lng: 127.0532,
    description:
      "신진 사진작가 15인의 봄 서울 그룹 전시. 도시와 사람을 담은 필름 사진.",
    price: "무료",
    tags: ["사진", "성수", "인디", "그룹전"],
  },

  // ─── 마켓 ────────────────────────────────────────────────────────────────
  {
    id: "m1",
    title: "성수 빈티지 마켓",
    category: "market",
    startDate: "2026-04-13",
    endDate: "2026-04-13",
    venueName: "서울숲 이벤트홀",
    address: "서울 성동구 뚝섬로 273",
    lat: 37.5448,
    lng: 127.0375,
    description:
      "성수동 빈티지 마켓. 의류, 소품, 아트워크, 핸드메이드 200여 셀러.",
    price: "무료 입장",
    tags: ["빈티지", "성수", "마켓", "핸드메이드"],
  },
  {
    id: "m2",
    title: "한남 플리마켓",
    category: "market",
    startDate: "2026-04-12",
    endDate: "2026-04-13",
    venueName: "한남동 문화거리",
    address: "서울 용산구 이태원로 240",
    lat: 37.5347,
    lng: 127.0007,
    description: "한남동 골목 플리마켓. 빈티지, 리빙, 푸드 등 다양한 카테고리.",
    price: "무료",
    tags: ["플리마켓", "한남", "주말", "빈티지"],
  },
  {
    id: "m3",
    title: "인사동 공예 마켓",
    category: "market",
    startDate: "2026-04-13",
    endDate: "2026-04-13",
    venueName: "인사동 쌈지길",
    address: "서울 종로구 인사동길 44",
    lat: 37.5742,
    lng: 126.9866,
    description:
      "전통 공예 장인들의 마켓. 도예, 목공예, 자수 작품과 먹거리 장터.",
    price: "무료",
    tags: ["공예", "인사동", "전통", "장인"],
  },
  {
    id: "m4",
    title: "마포 봄 먹거리 마켓",
    category: "market",
    startDate: "2026-04-19",
    endDate: "2026-04-20",
    venueName: "망원시장 근처 광장",
    address: "서울 마포구 망원동 460",
    lat: 37.556,
    lng: 126.9018,
    description: "봄 제철 식재료, 가공식품, 맛집 부스가 한데 모인 먹거리 마켓.",
    price: "무료 입장",
    tags: ["푸드", "마포", "먹거리", "주말"],
  },

  // ─── 파티 ────────────────────────────────────────────────────────────────
  {
    id: "pt1",
    title: "홍대 클럽데이",
    category: "party",
    startDate: "2026-04-05",
    endDate: "2026-04-30",
    venueName: "홍대 클럽 스트리트",
    address: "서울 마포구 와우산로29길",
    lat: 37.5543,
    lng: 126.9252,
    description: "매주 토요일 홍대 클럽 거리. 여러 클럽을 한 패스로 이동.",
    price: "15,000원",
    tags: ["클럽", "홍대", "파티", "토요일"],
  },
  {
    id: "pt2",
    title: "이태원 루프탑 봄 파티",
    category: "party",
    startDate: "2026-04-18",
    endDate: "2026-04-18",
    venueName: "Cakeshop Rooftop",
    address: "서울 용산구 이태원로27가길 42",
    lat: 37.5358,
    lng: 126.9956,
    description:
      "봄밤 이태원 루프탑 파티. 일렉트로닉·하우스 뮤직과 봄 시즌 오프닝.",
    price: "25,000원",
    tags: ["루프탑", "이태원", "일렉트로닉", "봄"],
  },
  {
    id: "pt3",
    title: "을지로 테크노 클럽 나이트",
    category: "party",
    startDate: "2026-04-12",
    endDate: "2026-04-12",
    venueName: "을지로 언더그라운드",
    address: "서울 중구 을지로 44",
    lat: 37.5665,
    lng: 126.9923,
    description: "을지로 레트로 공간의 테크노·하우스 파티. 국내외 DJ 라인업.",
    price: "20,000원",
    tags: ["테크노", "을지로", "클럽", "언더그라운드"],
  },
  {
    id: "pt4",
    title: "성수 브런치 소셜 모임",
    category: "party",
    startDate: "2026-04-13",
    endDate: "2026-04-13",
    venueName: "성수동 카페",
    address: "서울 성동구 성수이로 67",
    lat: 37.5462,
    lng: 127.0549,
    description:
      "성수동 브런치 소셜 모임. 새로운 사람들과 만나는 편안한 낮 파티.",
    price: "35,000원 (브런치 포함)",
    tags: ["브런치", "소셜", "성수", "네트워킹"],
  },
  {
    id: "pt5",
    title: "한남 하우스 파티 위크",
    category: "party",
    startDate: "2026-04-17",
    endDate: "2026-04-19",
    venueName: "한남동 프라이빗 스페이스",
    address: "서울 용산구 한남대로20길",
    lat: 37.536,
    lng: 127.002,
    description:
      "한남동 프라이빗 공간에서 열리는 하우스 파티 위크. 참여 신청 필수.",
    price: "30,000원",
    tags: ["하우스파티", "한남", "프라이빗", "소셜"],
  },

  // ─── jennagoround 모임 (events.js) ───────────────────────────────────────
  {
    id: "jg-9-260404",
    title: "BUTTER RUN",
    category: "party",
    startDate: "2026-04-04",
    endDate: "2026-04-04",
    venueName: "탄천 러닝 코스",
    address: "경기 성남시 분당구 탄천 일대 (복정역 출발)",
    lat: 37.4592,
    lng: 127.1278,
    description:
      "버텨야 돼 버터런, 막차 츌바알. 4/4 8AM–11AM · 코스: 복정역 출발 – 야탑 – 정자 해산. 러닝·벚꽃·베이글·사교 알러지 주의.",
    price: "문의",
    tags: ["런닝", "탄천", "모닝", "jennagoround"],
  },
  {
    id: "jg-1-260221",
    title: "여졍's 생월파티",
    category: "party",
    startDate: "2026-02-21",
    endDate: "2026-02-21",
    venueName: "강남구 (장소 비공개)",
    address: "서울 강남구",
    lat: 37.4981,
    lng: 127.0276,
    description:
      "도파민 디톡스 컨셉 생일 모임. 시끌벅적한 자극은 잠시 내려놓고 맛있는 것과 휴식. 막차 타고 집으로.",
    price: "문의",
    tags: ["생일", "소모임", "강남", "jennagoround"],
  },
  {
    id: "jg-2-260213",
    title: "Woo Yeon",
    category: "party",
    startDate: "2026-02-13",
    endDate: "2026-02-13",
    venueName: "영등포구 모임",
    address: "서울 영등포구",
    lat: 37.5189,
    lng: 126.9025,
    description: "영등포에서 열린 jennagoround 정기 모임.",
    price: "문의",
    tags: ["게더링", "영등포", "jennagoround"],
  },
  {
    id: "jg-case-251101",
    title: "Case 1101",
    category: "party",
    startDate: "2025-11-01",
    endDate: "2025-11-01",
    venueName: "서초구 네트워킹",
    address: "서울 서초구",
    lat: 37.4837,
    lng: 127.0324,
    description: "대규모 네트워킹·파티 이벤트.",
    price: "문의",
    tags: ["네트워킹", "서초", "jennagoround"],
  },
  {
    id: "jg-jae-240830",
    title: "Jae Special Night 25",
    category: "party",
    startDate: "2024-08-30",
    endDate: "2024-08-30",
    venueName: "송파구",
    address: "서울 송파구",
    lat: 37.5145,
    lng: 127.1058,
    description: "Jae Special Night 시리즈.",
    price: "문의",
    tags: ["파티", "송파", "jennagoround"],
  },
  {
    id: "jg-8-251018",
    title: "Jae Special Night",
    category: "party",
    startDate: "2025-10-18",
    endDate: "2025-10-18",
    venueName: "용산구",
    address: "서울 용산구",
    lat: 37.5326,
    lng: 126.9903,
    description: "용산에서 열린 스페셜 나이트.",
    price: "문의",
    tags: ["네트워킹", "용산", "jennagoround"],
  },
  {
    id: "jg-tot-241101",
    title: "TOT 24",
    category: "party",
    startDate: "2024-11-01",
    endDate: "2024-11-01",
    venueName: "용산구",
    address: "서울 용산구",
    lat: 37.5401,
    lng: 126.9724,
    description: "TOT 시리즈 모임.",
    price: "문의",
    tags: ["소모임", "용산", "jennagoround"],
  },
  {
    id: "jg-jae-230730",
    title: "Jae Special Night 24",
    category: "party",
    startDate: "2023-07-30",
    endDate: "2023-07-30",
    venueName: "강남구",
    address: "서울 강남구",
    lat: 37.5012,
    lng: 127.0394,
    description: "강남에서 열린 Jae Special Night.",
    price: "문의",
    tags: ["네트워킹", "강남", "jennagoround"],
  },
  {
    id: "jg-tot-221029",
    title: "TOT 22",
    category: "party",
    startDate: "2022-10-29",
    endDate: "2022-10-29",
    venueName: "용산구",
    address: "서울 용산구",
    lat: 37.528,
    lng: 126.996,
    description: "TOT 22 모임.",
    price: "문의",
    tags: ["소모임", "용산", "jennagoround"],
  },
  {
    id: "jg-7-211029",
    title: "Halloween Party",
    category: "party",
    startDate: "2021-10-29",
    endDate: "2021-10-29",
    venueName: "용산구",
    address: "서울 용산구",
    lat: 37.5365,
    lng: 126.985,
    description: "할로윈 파티.",
    price: "문의",
    tags: ["할로윈", "용산", "jennagoround"],
  },

  // ─── 모임 · 소셜 (추가) ──────────────────────────────────────────────────
  {
    id: "pt6",
    title: "강남 스터디 카페 네트워킹",
    category: "party",
    startDate: "2026-03-01",
    endDate: "2026-06-30",
    venueName: "강남역 인근 스터디카페",
    address: "서울 강남구 강남대로 396",
    lat: 37.4979,
    lng: 127.0276,
    description: "매주 수요일 저녁 IT·창업 이야기 나누는 소규모 네트워킹.",
    price: "음료 각자",
    tags: ["네트워킹", "스터디", "강남"],
  },
  {
    id: "pt7",
    title: "종로 보드게임 나이트",
    category: "party",
    startDate: "2026-04-01",
    endDate: "2026-05-31",
    venueName: "보드게임 카페",
    address: "서울 종로구 종로3가",
    lat: 37.5704,
    lng: 126.991,
    description: "금요일 밤 보드게임 번개. 초보도 환영.",
    price: "12,000원",
    tags: ["보드게임", "종로", "금요일"],
  },
  {
    id: "pt8",
    title: "연남동 와인 소셜",
    category: "party",
    startDate: "2026-04-10",
    endDate: "2026-04-10",
    venueName: "연남동 와인바",
    address: "서울 마포구 연남로 45",
    lat: 37.5612,
    lng: 126.9235,
    description: "와인 한 잔 하며 직장·취미 이야기하는 소셜 모임.",
    price: "참가비 40,000원",
    tags: ["와인", "연남", "소셜"],
  },
  {
    id: "pt9",
    title: "잠실 러닝 크루 모닝런",
    category: "party",
    startDate: "2026-04-01",
    endDate: "2026-10-31",
    venueName: "잠실 한강공원",
    address: "서울 송파구 올림픽로 480",
    lat: 37.5148,
    lng: 127.087,
    description: "토요일 7시 5km 페이스 러닝 후 커피.",
    price: "무료",
    tags: ["러닝", "잠실", "크루"],
  },
  {
    id: "pt10",
    title: "건대 보드카페 언어교환",
    category: "party",
    startDate: "2026-04-05",
    endDate: "2026-04-26",
    venueName: "건대입구역 인근",
    address: "서울 광진구 아차산로 30",
    lat: 37.5407,
    lng: 127.0692,
    description: "한영·한일 언어교환 번개. 2시간 회차제.",
    price: "음료 1잔 포함 15,000원",
    tags: ["언어교환", "건대", "주말"],
  },
  {
    id: "pt11",
    title: "압구정 브런치 북클럽",
    category: "party",
    startDate: "2026-04-06",
    endDate: "2026-06-29",
    venueName: "압구정 카페",
    address: "서울 강남구 압구정로 123",
    lat: 37.5272,
    lng: 127.0285,
    description: "2주마다 일요일 11시 에세이·소설 독서 토론.",
    price: "브런치 각자",
    tags: ["북클럽", "압구정", "독서"],
  },
  {
    id: "pt12",
    title: "노원 볼링 번개",
    category: "party",
    startDate: "2026-04-11",
    endDate: "2026-04-11",
    venueName: "노원 볼링장",
    address: "서울 노원구 상계로 77",
    lat: 37.6542,
    lng: 127.0565,
    description: "초보도 OK. 2게임 + 간단 식사.",
    price: "25,000원",
    tags: ["볼링", "노원", "번개"],
  },
  {
    id: "pt13",
    title: "여의도 애프터눈 티 모임",
    category: "party",
    startDate: "2026-04-20",
    endDate: "2026-04-20",
    venueName: "여의도 호텔 라운지",
    address: "서울 영등포구 여의동로 28",
    lat: 37.5258,
    lng: 126.9245,
    description: "주말 오후 티 세트와 라이트한 네트워킹.",
    price: "55,000원",
    tags: ["티", "여의도", "소셜"],
  },
  {
    id: "pt14",
    title: "신촌 인디 영화 토론",
    category: "party",
    startDate: "2026-04-08",
    endDate: "2026-06-24",
    venueName: "신촌 독립영화관 인근",
    address: "서울 서대문구 신촌로 45",
    lat: 37.5598,
    lng: 126.9422,
    description: "격주 수요일 단편 상영 후 토론.",
    price: "영화 티켓 각자",
    tags: ["영화", "신촌", "토론"],
  },
  {
    id: "pt15",
    title: "판교 테크 밋업",
    category: "party",
    startDate: "2026-04-16",
    endDate: "2026-04-16",
    venueName: "판교 스타트업 캠퍼스",
    address: "경기 성남시 분당구 판교역로 146",
    lat: 37.3947,
    lng: 127.1112,
    description: "프로덕트·ML 직군 라이트닝 토크 & 네트워킹.",
    price: "무료",
    tags: ["테크", "판교", "밋업"],
  },
  {
    id: "pt16",
    title: "한강 선셋 피크닉",
    category: "party",
    startDate: "2026-04-25",
    endDate: "2026-04-25",
    venueName: "반포 한강공원",
    address: "서울 서초구 반포동 115-5",
    lat: 37.5095,
    lng: 127.006,
    description: "돗자리·간단 안주 나눠 먹는 선셋 모임.",
    price: "1만 원 (공금)",
    tags: ["피크닉", "한강", "선셋"],
  },
  {
    id: "pt17",
    title: "을지로 필름 카메라 산책",
    category: "party",
    startDate: "2026-04-12",
    endDate: "2026-04-12",
    venueName: "을지로3가역 집결",
    address: "서울 중구 을지로3가",
    lat: 37.5661,
    lng: 126.9918,
    description: "필름 카메라 들고 골목 사진 산책 후 현상 이야기.",
    price: "무료",
    tags: ["사진", "을지로", "산책"],
  },
  {
    id: "pt18",
    title: "송파 요가 & 차 모임",
    category: "party",
    startDate: "2026-04-19",
    endDate: "2026-05-17",
    venueName: "잠실 요가 스튜디오",
    address: "서울 송파구 올림픽로 300",
    lat: 37.511,
    lng: 127.098,
    description: "일요일 오전 릴렉스 요가 후 허브티.",
    price: "30,000원",
    tags: ["요가", "송파", "힐링"],
  },
  {
    id: "pt19",
    title: "청량리 레트로 카페 모임",
    category: "party",
    startDate: "2026-04-14",
    endDate: "2026-04-14",
    venueName: "경동시장 인근",
    address: "서울 동대문구 왕산로 1",
    lat: 37.5806,
    lng: 127.048,
    description: "90년대 감성 카페에서 추억·음악 이야기.",
    price: "음료 각자",
    tags: ["레트로", "청량리", "카페"],
  },
  {
    id: "pt20",
    title: "서울숲 봄 피크닉 네트워킹",
    category: "party",
    startDate: "2026-04-26",
    endDate: "2026-04-26",
    venueName: "서울숲",
    address: "서울 성동구 뚝섬로 273",
    lat: 37.5443,
    lng: 127.0378,
    description: "봄꽃 시즌 가벼운 자기소개와 명함 교환.",
    price: "도시락 각자",
    tags: ["피크닉", "서울숲", "네트워킹"],
  },

  // ─── 축제 (추가) ──────────────────────────────────────────────────────────
  {
    id: "f5",
    title: "서울 거리예술 축제",
    category: "festival",
    startDate: "2026-05-02",
    endDate: "2026-05-04",
    venueName: "대학로 마로니에공원",
    address: "서울 종로구 대학로 102",
    lat: 37.581,
    lng: 127.002,
    description: "퍼포먼스·마임·서커스가 거리를 채우는 봄 거리예술제.",
    price: "무료",
    tags: ["거리예술", "대학로", "퍼포먼스"],
  },
  {
    id: "f6",
    title: "반포 한강 불꽃 축제 프리뷰",
    category: "festival",
    startDate: "2026-04-25",
    endDate: "2026-04-26",
    venueName: "반포한강공원",
    address: "서울 서초구 반포동",
    lat: 37.508,
    lng: 127.011,
    description: "야간 조명·버스킹·푸드트럭이 함께하는 한강 축제.",
    price: "무료",
    tags: ["한강", "야간", "버스킹"],
  },
  {
    id: "f7",
    title: "북촌 한옥 문화 주간",
    category: "festival",
    startDate: "2026-04-21",
    endDate: "2026-04-27",
    venueName: "북촌 한옥마을",
    address: "서울 종로구 가회동",
    lat: 37.5826,
    lng: 126.985,
    description: "한옥 체험·전통 공예·야간 개방 코스.",
    price: "일부 유료",
    tags: ["한옥", "북촌", "전통"],
  },
  {
    id: "f8",
    title: "노들섬 라이브 뮤직 위크",
    category: "festival",
    startDate: "2026-05-09",
    endDate: "2026-05-10",
    venueName: "노들섬",
    address: "서울 영등포구 노들로 195",
    lat: 37.512,
    lng: 126.952,
    description: "한강 섬에서 펼쳐지는 인디·재즈 라이브.",
    price: "무료",
    tags: ["라이브", "노들섬", "인디"],
  },
  {
    id: "f9",
    title: "광화문 광장 시민 축제",
    category: "festival",
    startDate: "2026-05-15",
    endDate: "2026-05-17",
    venueName: "광화문광장",
    address: "서울 종로구 세종대로",
    lat: 37.5759,
    lng: 126.9768,
    description: "가족·친구와 함께하는 시민 참여형 야외 축제.",
    price: "무료",
    tags: ["광화문", "가족", "야외"],
  },

  // ─── 팝업 (추가) ─────────────────────────────────────────────────────────
  {
    id: "p7",
    title: "삼성 갤럭시 체험 팝업",
    category: "popup",
    startDate: "2026-04-20",
    endDate: "2026-05-15",
    venueName: "코엑스 야외광장",
    address: "서울 강남구 영동대로 513",
    lat: 37.512,
    lng: 127.0595,
    description: "신제품 체험존·굿즈 증정.",
    price: "무료",
    tags: ["테크", "코엑스", "체험"],
  },
  {
    id: "p8",
    title: "성수 핸드메이드 주얼리 팝업",
    category: "popup",
    startDate: "2026-04-22",
    endDate: "2026-05-05",
    venueName: "성수 연무장길",
    address: "서울 성동구 연무장길 38",
    lat: 37.5455,
    lng: 127.056,
    description: "국내 디자이너 주얼리 한정 판매.",
    price: "무료 입장",
    tags: ["주얼리", "성수", "핸드메이드"],
  },
  {
    id: "p9",
    title: "연트럴파크 뷰티 팝업",
    category: "popup",
    startDate: "2026-04-18",
    endDate: "2026-05-01",
    venueName: "더현대 서울",
    address: "서울 영등포구 여의대로 108",
    lat: 37.5264,
    lng: 126.9282,
    description: "클린뷰티 브랜드 샘플링·메이크업 클래스.",
    price: "무료",
    tags: ["뷰티", "여의도", "샘플링"],
  },
  {
    id: "p10",
    title: "한남 리빙 페어 팝업",
    category: "popup",
    startDate: "2026-04-25",
    endDate: "2026-05-10",
    venueName: "한남동 쇼룸",
    address: "서울 용산구 한남대로 130",
    lat: 37.534,
    lng: 127.001,
    description: "인테리어 소품·조명 브랜드 쇼케이스.",
    price: "사전 예약",
    tags: ["리빙", "한남", "인테리어"],
  },

  // ─── 콘서트 (추가) ───────────────────────────────────────────────────────
  {
    id: "c6",
    title: "블루스퀘어 인디 쇼케이스",
    category: "concert",
    startDate: "2026-04-25",
    endDate: "2026-04-25",
    venueName: "블루스퀘어",
    address: "서울 용산구 이태원로 294",
    lat: 37.5338,
    lng: 126.997,
    description: "신인 인디 밴드 6팀 라이브.",
    price: "44,000원",
    tags: ["인디", "용산", "쇼케이스"],
  },
  {
    id: "c7",
    title: "롤링홀 어쿠스틱 나이트",
    category: "concert",
    startDate: "2026-04-30",
    endDate: "2026-04-30",
    venueName: "롤링홀",
    address: "서울 마포구 어울마당로 35",
    lat: 37.555,
    lng: 126.925,
    description: "어쿠스틱 세션 3팀 공연.",
    price: "33,000원",
    tags: ["어쿠스틱", "홍대", "라이브"],
  },
  {
    id: "c8",
    title: "롯데콘서트홀 실내악 시리즈",
    category: "concert",
    startDate: "2026-05-03",
    endDate: "2026-05-03",
    venueName: "롯데콘서트홀",
    address: "서울 송파구 올림픽로 240",
    lat: 37.5115,
    lng: 127.099,
    description: "현대 실내악 작품집 공연.",
    price: "40,000원~",
    tags: ["실내악", "잠실", "클래식"],
  },

  // ─── 전시 (추가) ─────────────────────────────────────────────────────────
  {
    id: "e6",
    title: "서울시립미술관 기획전",
    category: "exhibition",
    startDate: "2026-04-01",
    endDate: "2026-07-20",
    venueName: "서울시립미술관",
    address: "서울 중구 덕수궁길 61",
    lat: 37.5642,
    lng: 126.9738,
    description: "동시대 아시아 작가 회화·설치 작품.",
    price: "무료~",
    tags: ["미술", "덕수궁", "기획전"],
  },
  {
    id: "e7",
    title: "DDP 미디어 라운지",
    category: "exhibition",
    startDate: "2026-04-15",
    endDate: "2026-06-15",
    venueName: "DDP",
    address: "서울 중구 을지로 281",
    lat: 37.5665,
    lng: 127.009,
    description: "인터랙티브 LED·사운드 설치.",
    price: "15,000원",
    tags: ["미디어", "DDP", "인터랙티브"],
  },
  {
    id: "e8",
    title: "리움 미술관 컬렉션전",
    category: "exhibition",
    startDate: "2026-03-15",
    endDate: "2026-08-31",
    venueName: "리움미술관",
    address: "서울 용산구 이태원로55길 60",
    lat: 37.5384,
    lng: 126.999,
    description: "한국 근현대 작가 소장품 중심 전시.",
    price: "18,000원",
    tags: ["미술", "한남", "컬렉션"],
  },
  {
    id: "e9",
    title: "과천 국립현대미술관 특별전",
    category: "exhibition",
    startDate: "2026-04-10",
    endDate: "2026-09-01",
    venueName: "MMCA 과천",
    address: "경기 과천시 광명로 313",
    lat: 37.427,
    lng: 127.004,
    description: "대규모 조각·설치 야외 전시.",
    price: "4,000원",
    tags: ["미술", "과천", "야외"],
  },

  // ─── 마켓 (추가) ─────────────────────────────────────────────────────────
  {
    id: "m5",
    title: "노원 농수산 직거래 마켓",
    category: "market",
    startDate: "2026-04-26",
    endDate: "2026-04-27",
    venueName: "노원역 광장",
    address: "서울 노원구 상계동",
    lat: 37.6548,
    lng: 127.0568,
    description: "지역 농가 제철 채소·과일.",
    price: "무료 입장",
    tags: ["직거래", "노원", "제철"],
  },
  {
    id: "m6",
    title: "양재 플라워 마켓",
    category: "market",
    startDate: "2026-04-19",
    endDate: "2026-04-20",
    venueName: "양재천 일대",
    address: "서울 서초구 양재동",
    lat: 37.4705,
    lng: 127.038,
    description: "봄 꽃·화분·플라워 클래스.",
    price: "무료",
    tags: ["꽃", "양재", "봄"],
  },
  {
    id: "m7",
    title: "을지로 골동품 벼룩시장",
    category: "market",
    startDate: "2026-04-12",
    endDate: "2026-04-13",
    venueName: "을지로 골목",
    address: "서울 중구 을지로3가",
    lat: 37.5658,
    lng: 126.9915,
    description: "빈티지 소품·LP·카메라.",
    price: "무료",
    tags: ["빈티지", "을지로", "벼룩시장"],
  },
  {
    id: "m8",
    title: "청계천 야시장",
    category: "market",
    startDate: "2026-05-01",
    endDate: "2026-05-05",
    venueName: "청계천광장",
    address: "서울 종로구 청계천로",
    lat: 37.5692,
    lng: 126.9787,
    description: "야간 조명 아래 푸드·핸드메이드 부스.",
    price: "무료 입장",
    tags: ["야시장", "청계천", "야간"],
  },
  {
    id: "jj_smc_20260613",
    title: "SMC (Saturday Morning Crochet)",
    category: "market",
    startDate: "2026-06-13",
    endDate: "2026-06-13",
    dateConfidence: "confirmed",
    venueName: "서울 용산구 (세부 장소 추후 안내)",
    address: "서울특별시 용산구",
    lat: 37.5386,
    lng: 126.9654,
    description:
      "Welcome to Saturday Morning Crochet\n안녕하세요 😊\n\n혼자 뜨개질하다가 어느새 셋이 모여 뜨개질을 하고있어요\n이 따뜻한 취미를 더 많은 분들과 함께 나누고 싶어 이번 이벤트를 열게 되었습니다 🧶✨\n\n뜨개질이 처음이어도 괜찮아요!\n그냥 관심만 있어도 충분합니다 ☺️\n\n이번 모임은 미국인 친구들과 함께 진행하는 소셜링 모임이라\n영어와 한국어를 자연스럽게 섞어 대화하며\n언어 교환과 문화 교류도 함께 즐길 수 있어요! (두근)\n\n각자의 진행하시던 작업물을 가져와도 좋고,\n가볍게 빈손으로 오셔도 괜찮아요!\n\n실과 바늘은 저희가 준비해둘게요 🙂",
    price: "별도 안내",
    tags: ["크로셰", "뜨개질", "소모임", "언어 교환", "소셜링"],
    image: "img/event/260613_smc.png",
    homepage: "",
    source: "custom",
  },
];

// ── TourAPI 자동 수집 데이터 병합 ────────────────────────────────────────────
// city-events-api.js 로드 후 CITY_EVENTS에 추가 (중복 id 제거)
if (typeof TOUR_EVENTS !== 'undefined') {
    const existingIds = new Set(CITY_EVENTS.map(e => e.id));
    TOUR_EVENTS.forEach(ev => {
        if (!existingIds.has(ev.id)) {
            CITY_EVENTS.push(ev);
        }
    });
}
